# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: lxorb.Nib
PackageVersion: 0.13.0
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Nib
ReleaseDate: 2026-10-05
AppsAndFeaturesEntries:
- DisplayName: Nib
  Publisher: emilvinu
  ProductCode: Nib
InstallationMetadata:
  DefaultInstallLocation: '%LOCALAPPDATA%\Nib'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/lxorb/nibeditor/releases/download/v0.13.0/Nib-0.13.0-windows-x64-setup.exe
  InstallerSha256: 8CCBA5A3E8635B4DCEE0E5A3469F3A980825AC43FCB3DEE0F7C1B9C0725D686B
- Architecture: arm64
  InstallerUrl: https://github.com/lxorb/nibeditor/releases/download/v0.13.0/Nib-0.13.0-windows-arm64-setup.exe
  InstallerSha256: FF760096F89EE677B0D294B0867DA6DDBCE9B5FBB38328A6494A31056FACD01C
ManifestType: installer
ManifestVersion: 1.12.0
